disabled_rules: # rule identifiers turned on by default to exclude from running
  - line_length
  - cyclomatic_complexity
  - function_body_length

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - fastlane

identifier_name:
  min_length: # only min_length
    warning: 2 # only error